#!/usr/bin/env python3
"""
tier-stack.py — group STACK.md's recommendations into evidence tiers (#72).

The stage tables in STACK.md organize tools by *when* you use them (Plan, Implement,
…). This adds an orthogonal lens — *how much to trust each pick* — derived from each
tool's Evidence value (the Evidence column in COMPARISON.md, populated by #67), NOT
hand-assigned:

  Tier 1 — measured: ran hands-on, with metrics (MEASURED) or a smoke test (RUN).
  Tier 2 — review-based: read docs/source (REVIEW) or catalog-inferred (SOURCE-ONLY),
           not run hands-on. Graduating an eval (#68) promotes a tool to Tier 1.

The tier block lives between the TIERS markers in STACK.md and is fully regenerated
from data each run, so it cannot drift from the evidence. Place the markers once by
hand; this script only rewrites between them.

  ./tier-stack.py          # apply: regenerate the tier block in STACK.md
  ./tier-stack.py --check  # verify only: exit 1 if the block is stale; mutate nothing
"""
import os, re, sys, importlib.util
import catalog_lib

ROOT = os.path.dirname(os.path.abspath(__file__))
_spec = importlib.util.spec_from_file_location("backfill_evidence", os.path.join(ROOT, "backfill-evidence.py"))
bf = importlib.util.module_from_spec(_spec); _spec.loader.exec_module(bf)
ae = bf.ae

STACK = os.path.join(ROOT, "STACK.md")
START, END = "<!-- TIERS:START -->", "<!-- TIERS:END -->"
TIER1 = ("MEASURED", "RUN")
_LINK = re.compile(r"\|\s*\[([^\]]+)\]\((https://github\.com/[^)]+)\)")


def stack_tiers(text, amap=None):
    """(tier1, tier2) lists of (tool, evidence), in STACK appearance order. Evidence is
    looked up from the evals (same alias map backfill-evidence.py uses, injectable for
    tests — #199); a STACK tool with no eval resolves to SOURCE-ONLY → Tier 2."""
    if amap is None:
        amap = bf._build_alias_map()
    tier1, tier2, seen = [], [], set()
    for text_, url in _LINK.findall(text):
        if text_ in seen:
            continue
        seen.add(text_)
        keys = catalog_lib.alias_keys(text_, url)
        ev = next((amap[k] for k in keys if k in amap), "SOURCE-ONLY")
        (tier1 if ev in TIER1 else tier2).append((text_, ev))
    return tier1, tier2


def render(tier1, tier2):
    fmt = lambda items: ", ".join(f"{t} ({e})" for t, e in items) if items else "_none_"
    return (
        f"{START}\n"
        "## Evidence tiers\n\n"
        "How far each pick below has been validated — derived from its `Evidence` value "
        "(the Evidence column in [COMPARISON.md](COMPARISON.md)), **not** hand-assigned. "
        "Regenerated by `tier-stack.py`; do not edit between the markers. The stage tables "
        "further down are the same tools organized by *when* you use them.\n\n"
        f"**Tier 1 — measured ({len(tier1)}): install with confidence.** Run hands-on, with "
        "metrics (`MEASURED`) or at least a smoke test (`RUN`).\n\n"
        f"{fmt(tier1)}\n\n"
        f"**Tier 2 — review-based ({len(tier2)}): try at your own risk.** Evaluated by reading "
        "docs/source (`REVIEW`) or inferred from catalog metadata (`SOURCE-ONLY`), not run "
        "hands-on — graduating an eval ([#68](https://github.com/mattbutlerengineering/ai-tooling/issues/68)) "
        "promotes a tool to Tier 1.\n\n"
        f"{fmt(tier2)}\n"
        f"{END}"
    )


def apply(text, amap=None):
    if START not in text or END not in text:
        sys.stderr.write(f"tier-stack: markers {START} / {END} not found in STACK.md — add them once by hand.\n")
        sys.exit(2)
    block = render(*stack_tiers(text, amap))
    return re.sub(re.escape(START) + r".*?" + re.escape(END), lambda m: block, text, flags=re.S)


def main():
    check = "--check" in sys.argv[1:]
    text = open(STACK, encoding="utf-8").read()
    new = apply(text)
    if check:
        if new != text:
            print("tier-stack check: DRIFT — STACK.md evidence tiers are stale; run ./tier-stack.py")
            sys.exit(1)
        print("tier-stack check: OK — STACK.md evidence tiers match the Evidence data")
        sys.exit(0)
    if new != text:
        open(STACK, "w", encoding="utf-8").write(new)
        print("tier-stack: regenerated the Evidence tiers block in STACK.md")
    else:
        print("tier-stack: STACK.md already up to date")


if __name__ == "__main__":
    main()
